"""initial models

Revision ID: 5786ffbe074a
Revises: 
Create Date: 2026-03-04 20:11:51.614761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5786ffbe074a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('variety', sa.String(length=100), nullable=True),
    sa.Column('origin_region', sa.String(length=100), nullable=True),
    sa.Column('optimal_temp_min', sa.Float(), nullable=True),
    sa.Column('optimal_temp_max', sa.Float(), nullable=True),
    sa.Column('optimal_humidity', sa.Float(), nullable=True),
    sa.Column('water_requirement', sa.String(length=50), nullable=True),
    sa.Column('climate_resilience_score', sa.Integer(), nullable=True),
    sa.Column('growth_duration_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('greenhouse_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('co2_ppm', sa.Float(), nullable=True),
    sa.Column('light_lux', sa.Float(), nullable=True),
    sa.Column('soil_moisture', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_greenhouse_id'), 'sensor_readings', ['greenhouse_id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_table('crop_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('greenhouse_id', sa.String(length=50), nullable=False),
    sa.Column('crop_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expected_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', name='cyclestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_cycles_greenhouse_id'), 'crop_cycles', ['greenhouse_id'], unique=False)
    op.create_index(op.f('ix_crop_cycles_id'), 'crop_cycles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_cycles_id'), table_name='crop_cycles')
    op.drop_index(op.f('ix_crop_cycles_greenhouse_id'), table_name='crop_cycles')
    op.drop_table('crop_cycles')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_greenhouse_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
